### ISSUE TITLE
Analyzers/BuildCheck stabilization for NET 9.0

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10316]
### Context

MSBuild analyzers are going to be shipped as opt-in preview feature in NET 9. Since we are in late stage of NET 9 cycle, we should now shift focus from feature development to stabilization - testing, dogfooding and bugfixing.

### Objectives

* Dogfooding
  * [x] https://github.com/orgs/dotnet/projects/373?pane=issue&itemId=59805840
  * [x] Prepare test script and crowdsource team and vendors for testing 
* Bugfixing
  * Pri 1
     * [x]  https://github.com/dotnet/msbuild/issues/10176
     * [x] https://github.com/dotnet/msbuild/issues/10071
     * [x] https://github.com/dotnet/msbuild/issues/10131
     * [x] https://github.com/dotnet/msbuild/issues/10036
     * [x] https://github.com/dotnet/msbuild/issues/10429
     * [x] https://github.com/dotnet/msbuild/issues/10448
     * [x] https://github.com/dotnet/msbuild/issues/10475
  * Others
     * [ ] https://github.com/dotnet/msbuild/issues/10317 
     * [x] https://github.com/dotnet/msbuild/issues/10431
     * [ ] https://github.com/dotnet/msbuild/issues/10387
     * [x] https://github.com/dotnet/msbuild/issues/10427
     * [ ] https://github.com/dotnet/msbuild/issues/10449
     * [ ] https://github.com/dotnet/msbuild/issues/10414
