### ISSUE TITLE
MSBuild BuildCheck Theme - NET 9

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10323]
### Background

This is a groupping of investment into BuildCheck area.

### Work in context of this theme

* [ ] [Epic] https://github.com/dotnet/msbuild/issues/9829 - Watch and evaluate performance impact of changes
* [ ] [Epic] https://github.com/dotnet/msbuild/issues/9747 - Analyzers prototyping - Detect and skip restore (evaluation and execution)
* [ ] [Epic] https://github.com/dotnet/msbuild/issues/9628 - Analyzers prototyping - Configuration module
* [ ] [Epic] https://github.com/dotnet/msbuild/issues/10316 - Analyzers/BuildCheck stabilization for NET 9.0
* [ ] https://github.com/dotnet/msbuild/issues/10318 - Rename (Build)Analyzer -> BuildCheck
