### ISSUE TITLE
[Kitten] Kitten work - August/2024

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10479]
### Context

Rotation duty for infra/cross-team incidents handling
Script: [internal OneNote link](https://microsoft.sharepoint.com/teams/ManagedLanguagesIDE/_layouts/15/Doc.aspx?sourcedoc={7d9f33d9-b24b-4f26-951f-d2e84da540da}&action=edit&wd=target%28MSBuild.one%7C18a01e3f-c519-466b-b148-26f61517df55%2FKitten%20Duty%7C79e82c49-7bdf-444d-8587-545658f838ee%2F%29&wdorigin=703)
Previous: https://github.com/dotnet/msbuild/issues/10332

### Work

- no overflow from previous month

Current asks:
- [x] deploy install scripts for bash (@YuliiaKovalova for more details)
    - Blocked by https://github.com/dotnet/dnceng/issues/3783 - Fixed
    - PR for website created: https://github.com/dotnet/website/pull/6754 (we have linter errors in the script)
- [x] https://github.com/dotnet/msbuild/pull/10464 - handle servicing (@baronfel for more details)
- [x] (based on time availability, otherwise offload) https://github.com/dotnet/msbuild/issues/10021
   - Investigation done. Explanation and hints provided.
- [ ] refreshing and CG cleaning release branches: 17.11, 17.10, 17.8, 17.3, 17.0
   - 17.11 PR created: https://github.com/dotnet/msbuild/pull/10520
      - MS.IO.Redist wasn't updated as VS 17.11 still uses older version - track [Bug 2188396](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2188396) for updates
- [x] Unexpected warning/error MSB3202 #9986 
- [x] Publish MSBuild 17.11.2 packages for VSExtensibility team.
- [x] #10526 
- [x] Publish docs
   - https://dev.azure.com/msft-skilling/Content/_workitems/edit/300283
- [x] SymbolCheck: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2171791/ (up to 2171801)
- [ ] Migrate release pipelines (Due: Dec/31/2024)
   - [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224554
   - [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224556
   - [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224557
- [x] Investigate failed checks: https://github.com/dotnet/sdk/pull/43078
