### ISSUE TITLE
Telemetry NET 10.0 investments

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#10560]
### Context

Let's squeeze out more from existing telemtry and lets improve of what is available to us

### Suggested areas of investments

Yet to be reviewed by team!

 - [ ] Review telemetry related to MSBuild available to us in clusters today. Create overview documenting which clusters/tables are usable and what can we fetch. Put together some sample views (MSBuild usage stats, etc.)
 - [ ] Mounting MSBuild telemetry to VS listeners
 - [ ] Defining and exposing data-points for degraded functionality (exceptions, lags/hangs etc.)
 - [ ] Defining and exposing data-points for features usage

**Comment by JanProvaznik** [comment]
.NET 10 is closed
