### ISSUE TITLE
[Kitten] Kitten work - September/2024 - October/2024

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#10592]
### Context

Rotation duty for infra/cross-team incidents handling
Script: [internal OneNote link](https://microsoft.sharepoint.com/teams/ManagedLanguagesIDE/_layouts/15/Doc.aspx?sourcedoc={7d9f33d9-b24b-4f26-951f-d2e84da540da}&action=edit&wd=target%28MSBuild.one%7C18a01e3f-c519-466b-b148-26f61517df55%2FKitten%20Duty%7C79e82c49-7bdf-444d-8587-545658f838ee%2F%29&wdorigin=703)
Previous: https://github.com/dotnet/msbuild/issues/10479

### Work

(https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2188396) for updates
~~- [ ] Migrate release pipelines (Due: Dec/31/2024)~~
  ~~- [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224554~~
  ~~- [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224556~~
  ~~- [ ] https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2224557~~

It was moved to a separate ticket that JanPro is working on starting from October 16th

See if there is a fix for mirroring problems:
 - [x] https://github.com/dotnet/msbuild/issues/10591
 - [x] https://github.com/dotnet/msbuild/issues/10601
 - [x] https://github.com/dotnet/msbuild/issues/10617
 - [x] https://github.com/dotnet/msbuild/issues/10620

VS17.11 servicing:
- [x] Fix auth - https://github.com/dotnet/msbuild/pull/10654
- [x] Upgrade STJ to 8.0.4 - https://github.com/dotnet/msbuild/pull/10650

VS17.12 release:
- [ ] https://github.com/dotnet/msbuild/issues/10665
