### ISSUE TITLE
PerfStar NET 10.0 investments

### ISSUE THREAD

**Issue by AR-May** [dotnet/msbuild#11164]
### Context
Let's invest into PerfStar infrastructure. 
* Justification: see https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2057021
* Link to onepager PR: https://github.com/dotnet/msbuild/pull/11045
* Work track:  https://github.com/orgs/dotnet/projects/473

The NET 10 investment should consist of 2 parts:
 - Finalizing PerfStar V1, which includes fixing current CI bugs and PowerBI report.
 - Working on improvements with high value/effort rate.

Issues:
- [ ] https://github.com/dotnet/msbuild/issues/10825
- [ ] https://github.com/dotnet/msbuild/issues/10827
- [ ] https://github.com/dotnet/msbuild/issues/10828

**Comment by MattParkerDev** [comment]
Are the perfstar PowerBI reports public like the ASP.NET Core ones? :)

**Comment by baronfel** [comment]
No, but this is something I aim to push on as part of my [longer-term roadmap](https://hackmd.io/HYaeMjf_RJShf1H1-Z9yzw?view) for MSBuild.
