### ISSUE TITLE
Improve performance of CLI/SDK/MSBuild as it relates to the developer inner-loop

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/msbuild#5876]
### Summary
The .NET CLI, SDK, and MSBuild have a large impact on the inner-loop experience today. New .NET developers are often introduced via the CLI and perform the project creation, build, and launch operations from the command line. The SDK and MSBuild itself are present in all inner-loop scenarios whether it be CLI or IDE based.

Prior investigations have identified potential opportunities to improve performance of CLI interactions which should be further investigated and addressed as appropriate including but not limited to:

- Reduction in the launching of new processes and potential process reuse
- Optimizations of core SDK targets including NuGet restore and `ResolveAssemblyReference`
- Startup time optimizations  
- Revisiting of server timeouts (e.g. VBCSCompiler and rzr)
- Further workload-specific improvements to improve dotnet-watch performance
- General in-depth fundamentals push (profile, analyze, improve, repeat)

We should also explore opportunities for improving the CLI-based inner-loop UX through changes to the core commands involved, including revisiting defaults and potentially introducing new arguments or commands that improve the relevant scenarios, e.g. `dotnet run --watch`.

### User Stories & Issues

- [ ] [As a customer, I want implicitly cached references so that MSBUILD builds faster](https://github.com/dotnet/msbuild/issues/3139)
- [x] [As a customer, I want implicitly reduced launched processes so that MSBUILD is faster & consumes less resources](https://github.com/dotnet/msbuild/issues/5866)
- [ ] [As a customer, I want MSBUILD to start faster so that I wait negligible time to do my work](https://github.com/dotnet/msbuild/issues/5873)
- [ ] [As a customer, I want my applications to boot faster.](https://github.com/dotnet/runtime/issues/44598)
- [ ] [As a customer, speed up my first run of "dotnet new console"](https://github.com/dotnet/templating/issues/2743)
- [ ] As a customer, speed up my first build/run after doing dotnet new #5969 [internal one-pager](https://github.com/ladipro/one-pagers/pull/18)
- [ ] As a developer, I want my first time dotnet command to be faster dotnet/sdk#16998
- [ ] Investigate improvements to our disk usage on file timestamp checks #5972
- [ ] Investigate performance issues and explore solutions regarding CLI-related inner-loop scenarios dotnet/sdk#15218
- [x] Generate a RAR cache during SDK builds to improve first time RAR pass #5247
- [ ] [Measure and understand how time is spent currently in each phase / area of the build (ASP.NET Core projects)](https://github.com/dotnet/aspnetcore/issues/27271)
- [x] [Have SDK opt into using MSBuild's precomputed RAR cache](https://github.com/dotnet/installer/pull/10037)

**Comment by donJoseLuis** [comment]
Greetings @DamianEdwards , heads up on new child user story: [As a customer, speed up my first run of "dotnet new console"](https://github.com/dotnet/templating/issues/2743), based on the Brian's benchmarking follow ups.  Please advise if there is a better inner-loop parent for this user story & we'll gladly move it there.

**Comment by AR-May** [comment]
Team Triage: Closing the epic, as we are done with it.

**Comment by EliasCK** [comment]
> Team Triage: Closing the epic, as we are done with it.

But none of them was completed? What is the status on them?
