### ISSUE TITLE
BinaryFormatter Deprecation

### ISSUE THREAD

**Issue by Forgind** [dotnet/msbuild#6215]
## Motivativation

Moving away from [BinaryFormatter](https://aka.ms/BinaryFormatter) is a long running coordinated dotnet effort, [all first party code should be migrated away during .NET 8 timeframe](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#all-first-party-dotnet-org-code-bases-complete-migration-away-from-binaryformatter-net-8)

## Context

MSBuild is using BinaryFormatter in couple places as a fallback mechanism for de/serialization of more complex types (AppDomainSetup, Exceptions, ValueTypes etc.) as well as for de/serialization of custom, pluggable data (BuildEventArgs, Embedded resources)

### NET 8 - need to remove or developer-condition MSBuild usages of BinaryFormatter
- [x] **_GenerateResource_** Task (+ _resgen_) - Action plan needed - we can slowly deprecate this, but viable replacement needs to be thought through. **Cost: Unknown, Breaking: Yes**
  - [x] https://github.com/dotnet/msbuild/issues/8827 
- [x] _BinaryTranslator.TranslateDotNet_
  - [x] _TranslateException_ #8786 **Cost: M, Breaking: No**
  - [x] _AppDomainSetup_: https://github.com/dotnet/msbuild/issues/8922 needed for OutOfProc (TaskHostConfiguration) and Separate AppDomain Tasks (NodeConfiguration)) - it seems all we need are actually 'ConfigurationBytes' (https://github.com/dotnet/msbuild/blob/main/src/Shared/TaskLoader.cs#L95-L99) - so hopefully limited cost, but needs investigation. **Cost: S (TODO: detailed investigation to confirm), Breaking: No**
  - [x] _ValueType and ValueTypeArray_ task parameter types https://github.com/dotnet/msbuild/issues/8923 ([usage](https://github.com/dotnet/msbuild/blob/main/src/Shared/TaskParameter.cs#L282))  - We should be able to de/serialize without BinaryFormatter (Blittable types just be grabing the bytes, nonblittable by marshaling) - this should be relatively easy and isolated. **Cost: S, Breaking: No**
  - [x] _BuildEventArgs_
    - [x] MSBuild _first class citizen events_ - all serialized without BinaryFormatter (either via LogMessagePacketBase special handling, or via reflection discovered methods on types). **No work here**
    - [x] **_Custom BuildEventArgs_** #8823 - de/serialization approach from TranslateException should likely be way to go here. It's breaking though. **Cost: M, Breaking: Yes**
    - [x] #8825 Internal partners relying on custom BuildEventArgs need to be discovered (code search within GH, AzDO accross all our build event types), notified and brought to discussion (code search). **Cost: S-M**
    - [x] @Forgind already identified FxCop as relying on this. It's removed from VS, but will continue to ship as optional component via nuget (PoC: @mavasani(?) - so it might be FullFW only?)
    - [x] #9016
    - [x] #9008
    - [x] #9091
    - [x] #9355
  - [x] _Tests_ https://github.com/dotnet/msbuild/issues/8924
    - [x] _exceptions_ (just remove or move to TranslateException) **Cost: XS, Breaking: No**
    - [x] _ProfilerResult_ - most likely just remove, as this most likely uses only ITranslatable **Cost: XS, Breaking: No**
- [x] #8822  currently 11 usages. Hopefuly this doesn't need to be touched, or at worst just conditioned, otherwise cost might be significant. **Cost: Unknown, Breaking: Unknown**
- [x] _Unit tests_ https://github.com/dotnet/msbuild/issues/8925
  - [x] _Build.UnitTests_ - testing deserializing exceptions - should be moved to new eceptions de/serialization mechanism. **Cost: S, Breaking: No**
  - [x] _Framework.UnitTests_ - testing deserialization of EventArgs, AssemblyNameEx, CopyOnWriteDictionary - should be moved to new deserialization once implemented. **Cost: S, Breaking: No**
- [x] [_StateFileBase_ and extensions](https://github.com/dotnet/msbuild/pull/6350)
- [x] [_GetSDKReferenceFiles_ task](https://github.com/dotnet/msbuild/pull/6324)

### post NET 8 <a href="#post-net-8" id="post-net-8">#<a/>
- [x] https://github.com/dotnet/msbuild/issues/9300 - **Cost: XS, Breaking: Yes**
- [x] Communicate the .NET Framework breaking change to internal partners. Facilitate documentation update for VS 17.? - **Cost: S**
 - [ ] Remove serialization attributes, GetObjectData, (SerializationInfo, StreamingContext) constructors, etc. (to align with the [plan - deprecation of types](https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#remainder-of-legacy-serialization-infrastructure-obsoleted-net-9)) **Cost estimate: S-M**

**Comment by KirillOsenkov** [comment]
I'm working on getting rid of BinaryTranslator.TranslateDotNet. I'm writing custom manual serialization for various args which will be more efficient.

**Comment by Forgind** [comment]
@rokonec 👆

**Comment by rokonec** [comment]
@KirillOsenkov are those new 'custom manual serialization' be still supported by ITranslator?

**Comment by KirillOsenkov** [comment]
I’ll send a PR in the next day or two, for now I started with ProjectEvaluationStarted and ProjectEvaluationFinished, which currently go through TranslateDotNet. I haven’t looked at the other cases yet.

**Comment by Forgind** [comment]
Should not have closed this because of BinaryTranslator.TranslateDotNet

**Comment by KirillOsenkov** [comment]
I think I've at least moved all *BuildEventArgs classes off of using TranslateDotNet. So if you place a breakpoint and run a build, it should be used for BuildEventArgs serialization. If I missed a kind, let me know. I think TelemetryEventArgs potentially, but I don't know what that's for so I might have left it out.

But yes, there could be other types other than BuildEventArgs, so I didn't look into those.

**Comment by rolfbjarne** [comment]
I'm getting this when building a project with errors from the command line when using a recent version of .NET 8 (8.0.100-preview.5.23266.8):

```
 MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 90123:
 MSBUILD : error MSB4166: =====================
 MSBUILD : error MSB4166: 5/18/2023 4:56:48 PM
 MSBUILD : error MSB4166: System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
 MSBUILD : error MSB4166:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
 MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
 MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
 MSBUILD : error MSB4166: ===================
```

**Comment by rainersigwald** [comment]
@rolfbjarne very interesting! Can you share a repro? We didn't expect any .NET Core codepaths to hit this but we were clearly wrong.

**Comment by rolfbjarne** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	<PropertyGroup Condition="''">
	</PropertyGroup>
</Project>
```

```shell
$ donut --version
8.0.100-preview.5.23266.8

$ MSBUILDNOINPROCNODE=1 dotnet build MySimpleApp.csproj
MSBuild version 17.7.0-preview-23260-01+7f4bef8b4 for .NET
/Users/rolf/work/maccore/mono-master/xamarin-macios/tests/dotnet/MySimpleApp/macOS/MySimpleApp.csproj(6,17): error MSB4113: Specified condition "''" evaluates to "" instead of a boolean.
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/var/folders/43/h027tm1n101cdrq2_b6n9n2m0000gn/T/MSBuildTemprolf/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: /var/folders/43/h027tm1n101cdrq2_b6n9n2m0000gn/T/MSBuildTemprolf/MSBuild_pid-5527_75432f69f6fa4357a1cb60532f101677.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 5527:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 5/18/2023 6:00:21 PM
MSBUILD : error MSB4166: System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
MSBUILD : error MSB4166:    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildResult.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166:
MSBUILD : error MSB4166:

Build FAILED.
```

Note that when I ran into this originally, I didn't have `MSBUILDNOINPROCNODE` set, so that's not necessary for the issue to trigger (although I'm not sure how to force it without the env variable)

**Comment by rainersigwald** [comment]
Oh wow, that is DEFINITELY not a case I expected to fail here. Yikes. Thanks!

> Note that when I ran into this originally, I didn't have `MSBUILDNOINPROCNODE` set, so that's not necessary for the issue to trigger (although I'm not sure how to force it without the env variable)

I bet it's "multiproc build where the error originated in one of the worker processes".

**Comment by JanKrivanek** [comment]
related: https://github.com/dotnet/runtime/issues/43482

**Comment by Forgind** [comment]
Turn on warning in GenerateResource when building from the SDK:
https://github.com/dotnet/sdk/pull/32981

**Comment by JanKrivanek** [comment]
FYI: https://github.com/dotnet/sdk/pull/33227 (once merged, this should provide a workaround for the meantime)

**Comment by JanKrivanek** [comment]
Removing the BinFmt opt-in in sdk: https://github.com/dotnet/sdk/pull/34402
