### ISSUE TITLE
[Repo] Remove BOM and xml meta-tag from all files

### ISSUE THREAD

**Issue by Nirmal4G** [dotnet/msbuild#6645]
While #4779 tracks trailing white-space clean-up. This issue tracks removing BOM and xml meta-tag from all the file in the Repo.

#### Update EditorConfig

First, we should update EditorConfig to add `charset` and set it to `utf-8` to prevent future files marked with BOM (_**B**yte **O**rder **M**ark_).
We should also segregate files by category to enable charset or spacing changes one set at a time thereby reducing risk.

- [ ] Add `charset` to EditorConfig
- [ ] Segregate files by category

---

#### Remove BOM from all files in the Repo

As removing BOM from all the files at once is such a troublesome task, could fix many lingering issues related to BOM files in VS-IDE/MSBuild.
It could be breaking for several reasons too. MSBuild and VS have fixed several issues related to BOM but it is not complete.

So, with precaution, we'll remove BOM case by case basis knowing each category of BOM removed files won't cause trouble down the line!

- [ ] Remove BOM from sources (_cs_) files
- [ ] Remove BOM from scripts (_cmd/bat/ps1_) files
- [ ] Remove BOM from project (_\*proj/Directory.Build.\*_) files
- [ ] Remove BOM from shipping (_props/targets/tasks/xml/xslt_) files

---

#### Remove BOM from all files in the Repo

For xml meta-tag, the default has been utf-8 and v1 for so... long, I don't remember when. so, we don't need those meta-tag cluttering the top of the files.

```xml
<?xml version="1.0" encoding="utf-8"?>
```

- [ ] Remove xml meta-tag from all xml (and _xaml_) files

---

#### Notes

If there's anything I missed please let me know.

**Comment by sharwell** [comment]
I am **strongly** opposed to this change. I have observed numerous cases in the past where failure to include a BOM in UTF-8 content produced encoding errors in repository files, while never observing problems with the byte order mark included. I've also had to be the person trying to figure out what the original accented character was in the names of people participating briefly in a project, or specially-crafted string literals it tests that were lost because of a random failure to interpret content correctly.

**Comment by Nirmal4G** [comment]
You could find all sorts of issues (_by doing a simple web search_) regarding BOM (_with/without_). Even EditorConfig team and many others prefer BOM to be removed atleast with UTF-8. MSBuild and VS-IDE in recent years have improved a lot. By doing this change and self-hosting we could iron those remaining blockages.

**Comment by sharwell** [comment]
> You could find all sorts of issues (by doing a simple web search) regarding BOM (with/without). Even EditorConfig team and many others prefer BOM to be removed atleast with UTF-8.

I've been an active participant in this subject for many, many years. It's been my observation that the desire to remove BOM from source code scenarios generally stems from an idealized view of development tools, and not driven by an active need. Historically, one side of this option has led to occasional problems (utf-8) while the other side reliably has not (utf-8-bom). Considering the BOM is a reliable protection against future encoding errors, the historical default encoding for these files, _and_ a proper supported Unicode encoding with no evidence of impending future problems, there is simply no motivating scenario being presented for a change at this time.

**Comment by Nirmal4G** [comment]
> Considering the BOM is a reliable protection against future encoding errors

True but having a byte mark is also the source of much frustrations. We had problems with BOM through the text processing tools we use, though it's the tool author's responsibility to properly follow the Unicode spec but most don't. After careful testing, we removed BOM from all our codebases and we're happy. However, the issues you mentioned still remains but those are now corner cases that affect one/two files in every codebase; especially in localization testing.

Besides even Windows is letting users change its underlying system codepage to UTF-8. So, detecting UTF-8 without BOM has become much more important. So, adjusting our sources to work with that premise is not a bad thing.

**Comment by rainersigwald** [comment]
Team triage: thanks for bringing this up, but it doesn't seem to be worth the churn, given the concerns raised.

**Comment by Nirmal4G** [comment]
There are files (_yes, in each category I mentioned_) in the repo which doesn't have BOM. We haven't had much issues with them. Also, removing BOM doesn't cause any churn.

This issues tracks removals of un-necessary metadata in the files not just BOM. So, please keep it open.

**Comment by Nirmal4G** [comment]
@rainersigwald

> given the concerns raised.

Those concerns may be valid with MSBuild v14 and less but not now.

@sharwell

> in the past where failure to include a BOM...

May be then, but not now.




There are files (_yes, in each category I mentioned_) in the repo which doesn't have BOM. We haven't had much issues with them. Also, removing BOM doesn't cause any churn.

This issue also tracks removals of un-necessary metadata in the files not just BOM. If we choose not to remove something, I'll just update the issue. So, please keep it open.

**Comment by sharwell** [comment]
Hi @Nirmal4G,

I'm going to stay subscribed to this issue in case new information comes to light. However, keep in mind that my bar for making a change in this space is the same one I mentioned above:

> ... I would expect a detailed description of one or more scenarios where the BOM is actively impairing participation [in dotnet/msbuild] without an available workaround ...

Absent that, the issue is a request to change a subjective code style preference for which a preferred style has already been established. Like all other similar cases, we typically try to avoid unnecessary code churn by only considering the change if it originates with a project maintainer.

Thanks,
Sam
