### ISSUE TITLE
MSBUILD Server

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#7315]
Deliver the MSBUILD server requirements:

1. **_Server behavior_**: MSBuild is capable of running its scheduler and the "in-proc" node in a persistent server process. The process implements a communication mechanism to be able to accept build requests from other processes and return console logging.
1. **_Client behavior_**: The .NET CLI implements a communication mechanism to send build requests to MSBuild server instead of loading `Microsoft.Build` into the CLI process.
1. **_Full console fidelity_**: Console output of the client is indistinguishable from the current behavior.
1. **_Configurability_**: It is possible to opt out of the new behavior in case it causes unexpected issues.
1. **_Performance_**: The feature results in a significant speed up of the CLI inner loop. Incremental build of a simple ASP.NET Core app is at least 3x faster.

Child tasks:

- [x] [Design client-server communication protocol](https://github.com/dotnet/msbuild/issues/7370)
- [x] [Implement a new nodetype for the server process](https://github.com/dotnet/msbuild/issues/7371)
- [x] [Implement communication protocol in server](https://github.com/dotnet/msbuild/issues/7372)
- [x] [Implement communication protocol in the client library](https://github.com/dotnet/msbuild/issues/7374)
- [x] [Introduce a client-side activation/communication library](https://github.com/dotnet/msbuild/issues/7373)
- [x] [Cover MSBuild server with tests](https://github.com/dotnet/msbuild/issues/7377)
- [ ] [Consume the client library in dotnet CLI](https://github.com/dotnet/msbuild/issues/7375)
- [x] [MSBuild Server instrumentation](https://github.com/dotnet/msbuild/issues/7496)
- [x] [Memory Leak with MSBuild Server](https://github.com/dotnet/msbuild/issues/7639)
- [x] [Investigate MSBuild Server for memory leaks.](https://github.com/dotnet/msbuild/issues/7646)
- [x] [MSBUILD Server: cancellation.](https://github.com/dotnet/msbuild/issues/7647)
- [x] [MSBuild server needs to know Client Console configuration](https://github.com/dotnet/msbuild/issues/7658)
- [x] [Make MSBuild client API experimental](https://github.com/dotnet/msbuild/issues/7684)

## estimates
- 2 weeks for client work
- 2 for server work
- 3 weeks for remaining things
- 2 weeks buffer
