### ISSUE TITLE
ARM Benchmarking|Optimization

### ISSUE THREAD

**Issue by donJoseLuis** [dotnet/msbuild#7321]
# Background
Deliver "ARM perf" requirements

## Justification
- Customer impact - ensuring proper UXs for customers on ARM64 architecture.
- Needle moving (perf) - this is a time boxed effort to benchmark & optimize MSBUILD performance on ARM64 architecture.

## Tasks
- [x] https://github.com/dotnet/msbuild/issues/7888
- [x] https://github.com/dotnet/msbuild/issues/7889
- [x] https://github.com/dotnet/msbuild/issues/7891
