### ISSUE TITLE
Ability to redact secrets from MS BUILD binlogs

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8400]
Original story scoped down (the removed scope moved to 9101)

# Background

Functionality for redacting sensitive/secret data from binlogs

## Tasks
- [x] #9007
- [x] #9089
- [x] #9147
- [x] #9090
- [x] improve the redactor performance (`IBinlogProcessor` implementation) - https://github.com/dotnet/msbuild/issues/9261
- [x] add support for automatic detection of sensitive data (tokens) patterns - https://github.com/dotnet/msbuild/issues/9294
- [x] finalize contribution to Arcade - #9295
- [x] prototype contribution to binlog viewer - (no tracking item)

# Justification
- Decreasing sensitivity of binary log files shared by customers
- Decreasing sensitivity of binary log file artifacts produced by automations
Inspired by theme: "Cloud Native"

**Comment by JanKrivanek** [comment]
All subgoals are done. Redaction is now part of viewer, binlogtool, arcade.
