### ISSUE TITLE
Release 17.7

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#8896]
(adapted from #8611)

Preparation for the release:

- [x] When VS main snaps to `17.8`, create `vs17.7` branch
- [x] Create darc channel for `VS 17.8` if it doesn't already exist \
`darc add-channel --name "VS 17.8"`
- [x] Ping internal "First Responders" Teams channel to get the new channel made available as a promotion target (e.g. https://github.com/dotnet/arcade/issues/12150): https://github.com/dotnet/arcade/pull/12989
- [x] Remove the `main` to old release channel default channel \
`darc delete-default-channel --repo https://github.com/dotnet/msbuild --branch main --channel "VS 17.7"`
- [x] Associate the `main` branch with the next release channel \
`darc add-default-channel  --channel "VS 17.8" --branch main --repo https://github.com/dotnet/msbuild`
- [x] Check subscriptions for the current channel `VS 17.7` and update as necessary (for instance, SDK's `main` branch should usually be updated, whereas release branches often should not be \
`darc get-subscriptions --exact --source-repo https://github.com/dotnet/msbuild --channel "VS 17.7"`\
Update channel `VS 17.7` to `VS 17.8` for the sdk main subscription\
`darc update-subscription --id 5480c5ca-4fa6-4d8a-1987-08d9d606f30d`
- [x] Ensure that the current release channel `VS 17.7` is associated with the correct release branch\
`darc get-default-channels --source-repo https://github.com/dotnet/msbuild --branch vs17.7` \
if it is not, `darc add-default-channel  --channel "VS 17.7" --branch vs17.7 --repo https://github.com/dotnet/msbuild`
- [x] Fast-forward merge the correct commit (the one that is currently inserted to VS main) to the `vs17.7` branch \
`git push upstream 797fd829a374a880f63fd4eea4ea6990404c48f4:refs/heads/vs17.7` _Note the commit for future steps_
- [x] Update the branch merge flow in `dotnet/versions` to have the currently-in-servicing branches (extend dotnet/versions#867): https://github.com/dotnet/versions/pull/875
- [x] Fix OptProf data flow for the new vs17.7 branch
   - Run manually [OptProf](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=17389) pipeline for vs17.7 ('Run pipeline' in upper right)
   - Run the [MSBuild pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9434) for vs17.7 without OptProf (set `SkipApplyOptimizationData` variable in 'Advanced options' section of the 'Run pipeline' menu to `true`)
   - Run the [MSBuild pipeline](https://devdiv.visualstudio.com/DevDiv/_build?definitionId=9434) for vs17.7 with no extra vustomization - OptProf should succeed now
- [x] Update the [release-branch insertion release definition](https://dev.azure.com/devdiv/DevDiv/_releaseDefinition?definitionId=2153&_a=definition-variables) to have `InsertTargetBranch` `rel/d17.7`.
- [x] Prepare final branding PR for `vs17.7` but ⚠️ DO NOT MERGE IT YET ⚠️:
- [x] Create 17.8 branding PR, including public API baseline package version change (see https://github.com/dotnet/msbuild/pull/8116#discussion_r1049386978): #8949
- [x] Merge 17.8 branding PR
- [ ] ~Prepare QB-mode bug for final branding insertion in internal VS repo~
- [x] Merge final branding to `vs17.7` branch
- [x] Note down the build (will be helpful for requesting nuget packages publishing): https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=7967928&view=results 
- [ ] ~Get QB approval~
- [x] Merge to VS (babysit the automatically generated VS insertion PR https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequests for the MSBuild commit noted in above step): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/480342
- [x] Update the PackageValidationBaselineVersion to the latest released version (17.7.0) - this might require temporary addition of [build artifacts feed](https://github.com/dotnet/msbuild/blob/29397b577e3ec0fe0c7650c3ab0400909655dc88/NuGet.config#L9) as the new version is not yet added to the official feeds (this is post release). This can trigger a high severity CG error (https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/secure-supply-chain/how-to-securely-configure-package-source-files) - however it should be fine to keep this temporary feed untill the release.
- [x] Create 17.7 localization ticket: https://aka.ms/ceChangeLocConfig (requesting to flip localization from 17.6 to 17.7)
- [x] Disable the 17.6 localization - by setting [`EnableReleaseOneLocBuild`](https://github.com/dotnet/msbuild/blob/vs17.4/.vsts-dotnet.yml#L42) to `false`
- [x] Enable 17.7 localization - by setting [`EnableReleaseOneLocBuild`](https://github.com/dotnet/msbuild/blob/vs17.4/.vsts-dotnet.yml#L42) to `true`

ASAP On/After GA (based on release schedule (internal) https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/10097/Dev17-Release):

- [x] Push packages to nuget.org (not currently automated, contact dnceng - search "Publish MSBuild 17.6 to NuGet.org" email subject for template).
- [x] Remove the temporarily added [build feed from `nuget.config`](https://github.com/dotnet/msbuild/blob/29397b577e3ec0fe0c7650c3ab0400909655dc88/NuGet.config#L9) if it was added in the `Update the PackageValidationBaselineVersion` step
- [x] Update `main` subscriptions to the new channel (this can be done before or after release - depending on when the source repos from our previous - VS 17.7 - channle start to publish in the next - VS 17.8 - channel) \
`darc get-subscriptions --exact --target-repo https://github.com/dotnet/msbuild --target-branch main`
- [x] Create the 17.7 release
  - [x] Create tag (can be done upfront)
  ```
  git checkout <commit noted above>
  git tag v17.7.0
  git push upstream v17.7.0
  ```
  - [x] Create Release in Github with `Create Release from Tag` GH option (https://github.com/JanKrivanek/msbuild/releases/new?tag=v17.7.0) - the release notes can be prepopulated (`Generate Release Notes`)

**Comment by JanKrivanek** [comment]
FYI @rainersigwald
