### ISSUE TITLE
Epic: Structured logging

### ISSUE THREAD

**Issue by MichalPavlik** [dotnet/msbuild#9593]
This epic describes extension to the logging capabilities of the MSBuild application. The primary objective is to enhance the user experience and provide more control over the logging process. The proposed features include the ability to color log messages, scope log events, and set different verbosity levels for different loggers.

Tasks:
* [ ] Finalize document and get reviews
* [ ] #9594
* [ ] #9595
* [ ] Scoping (not decided yet)
* [ ] Granular verbosity (not decided yet)
* [x] #9596

**Comment by baronfel** [comment]
The latter - the current logging APIs require Task/Target authors to do layout/weight directly as part of message formatting. We need to provide them tools to _semantically_ describe these concepts on parts of a logging message, and then different `Logger` implementations can ignore/consume this semantic information as appropriate.

**Comment by rainersigwald** [comment]
Related: VS Code is allowing colorization in debug strings via the Debug Adapter Protocol: https://code.visualstudio.com/updates/v1_94#_support-for-data-colorization. Maybe there's a technique we can crib from there.
