### ISSUE TITLE
Analyzers prototyping

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9627]
### Context

https://github.com/dotnet/msbuild/issues/9380

### Goals

Functional prototype with sample analyzers

Subtasks:
 - [ ] #9628 - handles loading user settings from `.editorconfig` in a structured form. Optionally allows passing through unstructured custom key-value configurations for the rules
 - [ ] #9629 - Handles opt-in monitoring of overhead added byt the analyzers infra and individual analyzers
 - [ ] #9633
 - [ ] #9631 - indirection and abstraction layer between the actual data from MSBuild and their consumption in analyzers
 - [ ] #9632 - responsible for consuming the configuration and loaded modules running the registrations, pumping underlying data to analyzers and wrapping and routing the results
 - [ ] #9630 - identification and implementation
 - [ ] #9723
 - [x] #9729

Other work:
 - [x] #9734
 - [ ] #9747
 - [x] Detect current msbuild file and have it as part of analysis context - when asking for configuration (plus contexts might need to be preserved and switched)
 - [ ] Detect the root of the build - for analyzers that are checking references outside of the root of the build (https://github.com/orgs/dotnet/projects/373/views/1?pane=issue&itemId=55808682)
 - [ ] #9760
 - [ ] Canonicalize paths on Mac so analyzers can compare them ([this](https://github.com/dotnet/msbuild/blob/90bc89cd0a4dcc6fd2b609eea08fee3191e97652/src/Analyzers.UnitTests/EndToEndTests.cs#L114-L117) is the workaround for now) (https://github.com/orgs/dotnet/projects/373/views/1?pane=issue&itemId=55702688)

**Comment by JanKrivanek** [comment]
All work spun off and tracked separately
