### ISSUE TITLE
Analyzers prototyping - Detect and skip restore (evaluation and execution)

### ISSUE THREAD

**Issue by JanKrivanek** [dotnet/msbuild#9747]
### Context

#9627

Single build has multiple evaluation phases and extra execution phase to facilitate Restore. Running analyzers during those would be superflous - unnecessary perf burden, plus producing duplicite reports.
There might be cases where analysis during Restore is acutaly wanted - but let's skip such cases for now.

Let's *somehow* detect that current evaluation/execution is for Restore and defunct analyzers infra during that (or alternatively - let's detect it's for Build and enable only during that).
The detection will probably be needed in 2 places - first in the connector logger (for the analyzers getting data from BuildEventArgs) and in RequestBuilder - for analyzers getting data directly in the evaluating/executing node (this second place is not yet mounted in current analyzers prototype code - so can be skipped now).

![image](https://github.com/dotnet/msbuild/assets/3809076/9d7f287a-0cdf-4d27-a6b9-97d318900cc4)

### Work in this context:
 * [ ] https://github.com/dotnet/msbuild/pull/10172
 * [x] https://github.com/dotnet/msbuild/issues/10145
 * [ ] https://github.com/dotnet/msbuild/pull/10018
